version: '3'

services:
    db:
        container_name: databaseContainer
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: streaming
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadminContainer
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=db

volumes:
    db-data:


